### ISSUE TITLE
All downloads are redirected

### ISSUE THREAD

**Issue by codepuncher** [WPChill/download-monitor#741]
WP: 5.8.1
DLM: 4.4.6

All downloads are redirecting to the file rather than forcing a download.
This happens regardless of what is set in the post or what the `dlm_do_not_force` filter returns; all downloads are redirected.

I have narrowed this down to v4.4.5 being the cause; downgrading to 4.4.4 resolves the issue.

**Comment by giucu91** [comment]
fixed in 4.4.6

**Comment by codepuncher** [comment]
Hi @razvanaldea89 - I had the issue when using DLM 4.4.6. I narrowed it down to being caused in v4.4.5. How is it fixed in 4.4.6 if that is the version I experienced the issue on?

**Comment by razvanaldea89** [comment]
Hi @codepuncher ,

For some people version 4.4.6 had fixed the issue. I misunderstood the part with narrowing down to 4.4.5, as I asked again if in version 4.4.6 you are still experiencing issues. Sorry for that.

Yes, 4.4.6 in some scenarios ( like WordPress installation in some custom folder and set to be used as root ) doesn't fix the issue. We are preparing an update for that  and will be released soon.

Kind Regards!
Razvan

**Comment by codepuncher** [comment]
@razvanaldea89 What is the ETA for the fix? Or is there something we can do in the meantime for a temporary workaround?

Thanks

**Comment by razvanaldea89** [comment]
@codepuncher don't know exactly when the update will be deployed. In the meantime, could you please go to Downloads > Settings -> Advanced -> Miscellaneous and clear transients and see if this solves your problem?
